//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cubed.Forms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InspectorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InspectorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cubed.Forms.Resources.InspectorStrings", typeof(InspectorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient color.
        /// </summary>
        internal static string AmbientLight {
            get {
                return ResourceManager.GetString("AmbientLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string DefaultGroup {
            get {
                return ResourceManager.GetString("DefaultGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an object to edit properties.
        /// </summary>
        internal static string EmptyObject {
            get {
                return ResourceManager.GetString("EmptyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map environment.
        /// </summary>
        internal static string EnvironmentInfo {
            get {
                return ResourceManager.GetString("EnvironmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky, ambient color, fog, sounds.
        /// </summary>
        internal static string EnvironmentInfoDesc {
            get {
                return ResourceManager.GetString("EnvironmentInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment light.
        /// </summary>
        internal static string EnvLightGroup {
            get {
                return ResourceManager.GetString("EnvLightGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog color.
        /// </summary>
        internal static string FogColor {
            get {
                return ResourceManager.GetString("FogColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End distance.
        /// </summary>
        internal static string FogFar {
            get {
                return ResourceManager.GetString("FogFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        internal static string FogGroup {
            get {
                return ResourceManager.GetString("FogGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start distance.
        /// </summary>
        internal static string FogNear {
            get {
                return ResourceManager.GetString("FogNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level End.
        /// </summary>
        internal static string LevelEnd {
            get {
                return ResourceManager.GetString("LevelEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone that ends current level.
        /// </summary>
        internal static string LevelEndDesc {
            get {
                return ResourceManager.GetString("LevelEndDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes bright points on your map.
        /// </summary>
        internal static string LightDesc {
            get {
                return ResourceManager.GetString("LightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting point for player.
        /// </summary>
        internal static string PlayerDesc {
            get {
                return ResourceManager.GetString("PlayerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string ProjectAuthor {
            get {
                return ResourceManager.GetString("ProjectAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back (-Z).
        /// </summary>
        internal static string SkyBack {
            get {
                return ResourceManager.GetString("SkyBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom (-Y).
        /// </summary>
        internal static string SkyBottom {
            get {
                return ResourceManager.GetString("SkyBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front (+Z).
        /// </summary>
        internal static string SkyFront {
            get {
                return ResourceManager.GetString("SkyFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky.
        /// </summary>
        internal static string SkyGroup {
            get {
                return ResourceManager.GetString("SkyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left (-X).
        /// </summary>
        internal static string SkyLeft {
            get {
                return ResourceManager.GetString("SkyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right (+X).
        /// </summary>
        internal static string SkyRight {
            get {
                return ResourceManager.GetString("SkyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top (+Y).
        /// </summary>
        internal static string SkyTop {
            get {
                return ResourceManager.GetString("SkyTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient sounds.
        /// </summary>
        internal static string SoundGroup {
            get {
                return ResourceManager.GetString("SoundGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite.
        /// </summary>
        internal static string Sprite {
            get {
                return ResourceManager.GetString("Sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing to decorate maps.
        /// </summary>
        internal static string SpriteDesc {
            get {
                return ResourceManager.GetString("SpriteDesc", resourceCulture);
            }
        }
    }
}
