//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cubed.Forms.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InspectorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InspectorStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cubed.Forms.Resources.InspectorStrings", typeof(InspectorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Affected by fog.
        /// </summary>
        internal static string AffectedByFog {
            get {
                return ResourceManager.GetString("AffectedByFog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Affected by light.
        /// </summary>
        internal static string AffectedByLight {
            get {
                return ResourceManager.GetString("AffectedByLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ambient color.
        /// </summary>
        internal static string AmbientLight {
            get {
                return ResourceManager.GetString("AmbientLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Angle.
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blending.
        /// </summary>
        internal static string Blending {
            get {
                return ResourceManager.GetString("Blending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collision and bounds.
        /// </summary>
        internal static string BoundGroup {
            get {
                return ResourceManager.GetString("BoundGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Broken appearance.
        /// </summary>
        internal static string BrokenGroup {
            get {
                return ResourceManager.GetString("BrokenGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        internal static string DefaultGroup {
            get {
                return ResourceManager.GetString("DefaultGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select an object to edit properties.
        /// </summary>
        internal static string EmptyObject {
            get {
                return ResourceManager.GetString("EmptyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map environment.
        /// </summary>
        internal static string EnvironmentInfo {
            get {
                return ResourceManager.GetString("EnvironmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sky, ambient color, fog, sounds.
        /// </summary>
        internal static string EnvironmentInfoDesc {
            get {
                return ResourceManager.GetString("EnvironmentInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Environment light.
        /// </summary>
        internal static string EnvLightGroup {
            get {
                return ResourceManager.GetString("EnvLightGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Facing.
        /// </summary>
        internal static string Facing {
            get {
                return ResourceManager.GetString("Facing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fog color.
        /// </summary>
        internal static string FogColor {
            get {
                return ResourceManager.GetString("FogColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End distance.
        /// </summary>
        internal static string FogFar {
            get {
                return ResourceManager.GetString("FogFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fog.
        /// </summary>
        internal static string FogGroup {
            get {
                return ResourceManager.GetString("FogGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start distance.
        /// </summary>
        internal static string FogNear {
            get {
                return ResourceManager.GetString("FogNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level End.
        /// </summary>
        internal static string LevelEnd {
            get {
                return ResourceManager.GetString("LevelEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zone that ends current level.
        /// </summary>
        internal static string LevelEndDesc {
            get {
                return ResourceManager.GetString("LevelEndDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Makes bright points on your map.
        /// </summary>
        internal static string LightDesc {
            get {
                return ResourceManager.GetString("LightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Offset.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting point for player.
        /// </summary>
        internal static string PlayerDesc {
            get {
                return ResourceManager.GetString("PlayerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author.
        /// </summary>
        internal static string ProjectAuthor {
            get {
                return ResourceManager.GetString("ProjectAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project name.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scale.
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dimensions.
        /// </summary>
        internal static string SizeGroup {
            get {
                return ResourceManager.GetString("SizeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back (-Z).
        /// </summary>
        internal static string SkyBack {
            get {
                return ResourceManager.GetString("SkyBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom (-Y).
        /// </summary>
        internal static string SkyBottom {
            get {
                return ResourceManager.GetString("SkyBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Front (+Z).
        /// </summary>
        internal static string SkyFront {
            get {
                return ResourceManager.GetString("SkyFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sky.
        /// </summary>
        internal static string SkyGroup {
            get {
                return ResourceManager.GetString("SkyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left (-X).
        /// </summary>
        internal static string SkyLeft {
            get {
                return ResourceManager.GetString("SkyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right (+X).
        /// </summary>
        internal static string SkyRight {
            get {
                return ResourceManager.GetString("SkyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top (+Y).
        /// </summary>
        internal static string SkyTop {
            get {
                return ResourceManager.GetString("SkyTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Solid.
        /// </summary>
        internal static string Solid {
            get {
                return ResourceManager.GetString("Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound.
        /// </summary>
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Point that emits audio.
        /// </summary>
        internal static string SoundDesc {
            get {
                return ResourceManager.GetString("SoundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ambient sounds.
        /// </summary>
        internal static string SoundGroup {
            get {
                return ResourceManager.GetString("SoundGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sprite.
        /// </summary>
        internal static string Sprite {
            get {
                return ResourceManager.GetString("Sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thing to decorate maps.
        /// </summary>
        internal static string SpriteDesc {
            get {
                return ResourceManager.GetString("SpriteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Texture.
        /// </summary>
        internal static string Texture {
            get {
                return ResourceManager.GetString("Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tint.
        /// </summary>
        internal static string Tint {
            get {
                return ResourceManager.GetString("Tint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visual appearance.
        /// </summary>
        internal static string VisualGroup {
            get {
                return ResourceManager.GetString("VisualGroup", resourceCulture);
            }
        }
    }
}
