//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cubed.Forms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageBoxData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBoxData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cubed.Forms.Resources.MessageBoxData", typeof(MessageBoxData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string abortLabel {
            get {
                return ResourceManager.GetString("abortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project you are trying to open is broken! Do you want to proceed?.
        /// </summary>
        internal static string brokenProjectBody {
            get {
                return ResourceManager.GetString("brokenProjectBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken project.
        /// </summary>
        internal static string brokenProjectTitle {
            get {
                return ResourceManager.GetString("brokenProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonIgnore {
            get {
                object obj = ResourceManager.GetObject("buttonIgnore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonNegative {
            get {
                object obj = ResourceManager.GetObject("buttonNegative", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonPositive {
            get {
                object obj = ResourceManager.GetObject("buttonPositive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonRetry {
            get {
                object obj = ResourceManager.GetObject("buttonRetry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancelLabel {
            get {
                return ResourceManager.GetString("cancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap errorIcon {
            get {
                object obj = ResourceManager.GetObject("errorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been changed outside editor. Do you want to reload it from disk?.
        /// </summary>
        internal static string fileChangedBody {
            get {
                return ResourceManager.GetString("fileChangedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File changed.
        /// </summary>
        internal static string fileChangedTitle {
            get {
                return ResourceManager.GetString("fileChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File removed from disk. Do you want to keep in editor?.
        /// </summary>
        internal static string fileRemovedBody {
            get {
                return ResourceManager.GetString("fileRemovedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File removed.
        /// </summary>
        internal static string fileRemovedTitle {
            get {
                return ResourceManager.GetString("fileRemovedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string ignoreLabel {
            get {
                return ResourceManager.GetString("ignoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap infoIcon {
            get {
                object obj = ResourceManager.GetObject("infoIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify folder name:.
        /// </summary>
        internal static string newFolderBody {
            get {
                return ResourceManager.GetString("newFolderBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string newFolderTitle {
            get {
                return ResourceManager.GetString("newFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify item name:.
        /// </summary>
        internal static string newItemBody {
            get {
                return ResourceManager.GetString("newItemBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Entry.
        /// </summary>
        internal static string newItemTitle {
            get {
                return ResourceManager.GetString("newItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify preset file name:.
        /// </summary>
        internal static string newPrefabBody {
            get {
                return ResourceManager.GetString("newPrefabBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create preset.
        /// </summary>
        internal static string newPrefabTitle {
            get {
                return ResourceManager.GetString("newPrefabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string noLabel {
            get {
                return ResourceManager.GetString("noLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string okLabel {
            get {
                return ResourceManager.GetString("okLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap questionIcon {
            get {
                object obj = ResourceManager.GetObject("questionIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete %FILE%?.
        /// </summary>
        internal static string removeBody {
            get {
                return ResourceManager.GetString("removeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        internal static string removeTitle {
            get {
                return ResourceManager.GetString("removeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify new name for entry:.
        /// </summary>
        internal static string renameBody {
            get {
                return ResourceManager.GetString("renameBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        internal static string renameTitle {
            get {
                return ResourceManager.GetString("renameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string retryLabel {
            get {
                return ResourceManager.GetString("retryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File contains unsaved changes. Do you want to save them?.
        /// </summary>
        internal static string saveChangesBody {
            get {
                return ResourceManager.GetString("saveChangesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        internal static string saveChangesTitle {
            get {
                return ResourceManager.GetString("saveChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warningIcon {
            get {
                object obj = ResourceManager.GetObject("warningIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yesLabel {
            get {
                return ResourceManager.GetString("yesLabel", resourceCulture);
            }
        }
    }
}
